[versions]
micronaut-serde="1.0.1"
zalando-problem="0.27.1"

[libraries]
micronaut-serde-processor = { module = "io.micronaut.serde:micronaut-serde-processor", version.ref = "micronaut-serde" }
micronaut-serde-api = { module = "io.micronaut.serde:micronaut-serde-api", version.ref = "micronaut-serde" }
micronaut-serde-jackson = { module = "io.micronaut.serde:micronaut-serde-jackson", version.ref = "micronaut-serde" }
micronaut-validation = { module = "io.micronaut:micronaut-validation" }
micronaut-http-server = { module = "io.micronaut:micronaut-http-server" }
micronaut-http-server-netty = { module = "io.micronaut:micronaut-http-server-netty" }
micronaut-http-client = { module = "io.micronaut:micronaut-http-client" }
micronaut-inject-java = { module = "io.micronaut:micronaut-inject-java" }
zalando-problem = { module = "org.zalando:problem", version.ref = "zalando-problem" }
logback-classic = { module = "ch.qos.logback:logback-classic" }
